[
{
        "amount_to_invoice": 4990,
        "amount_total": 4990,
        "amount_untaxed": 4536.36,
        "create_date": "2024-06-13 03:31:05",
        "delivery_status": "pending",
        "internal_note_display": "<p>Installation Service - Qty: 1.0<br>WAA Full House Healthy Water V2-B (w filters) - Qty: 1.0<br>WAA Healthy Under Sink RO2 (w filters) - Qty: 1.0</p>",
        "name": "S099991",
        "partner_id_contact_address": "10 Saligna Way\n\nDayton WA 6055\nAustralia",
        "partner_id_display_name": "Parvinder Singh",
        "partner_id_phone": "+61 401 196 596",
        "state": "sale",
        "x_studio_commission_paid": 0,
        "x_studio_invoice_payment_status": "0",
        "x_studio_payment_type": "Finance - Humm",
        "x_studio_referrer_processed": 0,
        "x_studio_sales_rep_1": "Terry Warby",
        "x_studio_sales_source": "Company Lead",
        "order_line": []
    },
    {
        "amount_to_invoice": 4990,
        "amount_total": 4990,
        "amount_untaxed": 4536.36,
        "create_date": "2024-06-13 03:31:05",
        "delivery_status": "pending",
        "internal_note_display": "<p>Installation Service - Qty: 1.0<br>WAA Full House Healthy Water V2-B (w filters) - Qty: 1.0<br>WAA Healthy Under Sink RO2 (w filters) - Qty: 1.0</p>",
        "name": "S099992,
        "partner_id_contact_address": "10 Saligna Way\n\nDayton WA 6055\nAustralia",
        "partner_id_display_name": "Parvinder Singh",
        "partner_id_phone": "+61 401 196 596",
        "state": "sale",
        "x_studio_commission_paid": 0,
        "x_studio_invoice_payment_status": "0",
        "x_studio_payment_type": "Finance - Humm",
        "x_studio_referrer_processed": 0,
        "x_studio_sales_rep_1": "Terry Warby",
        "x_studio_sales_source": "Company Lead",
        "order_line": []
    },
    {
        "amount_to_invoice": 4990,
        "amount_total": 4990,
        "amount_untaxed": 4536.36,
        "create_date": "2024-06-13 03:31:05",
        "delivery_status": "pending",
        "internal_note_display": "<p>Installation Service - Qty: 1.0<br>WAA Full House Healthy Water V2-B (w filters) - Qty: 1.0<br>WAA Healthy Under Sink RO2 (w filters) - Qty: 1.0</p>",
        "name": "S099993",
        "partner_id_contact_address": "10 Saligna Way\n\nDayton WA 6055\nAustralia",
        "partner_id_display_name": "Parvinder Singh",
        "partner_id_phone": "+61 401 196 596",
        "state": "sale",
        "x_studio_commission_paid": 0,
        "x_studio_invoice_payment_status": "0",
        "x_studio_payment_type": "Finance - Humm",
        "x_studio_referrer_processed": 0,
        "x_studio_sales_rep_1": "Terry Warby",
        "x_studio_sales_source": "Company Lead",
        "order_line": []
    },
    {
        "amount_to_invoice": 4990,
        "amount_total": 4990,
        "amount_untaxed": 4536.36,
        "create_date": "2024-06-13 03:31:05",
        "delivery_status": "pending",
        "internal_note_display": "<p>Installation Service - Qty: 1.0<br>WAA Full House Healthy Water V2-B (w filters) - Qty: 1.0<br>WAA Healthy Under Sink RO2 (w filters) - Qty: 1.0</p>",
        "name": "S099994",
        "partner_id_contact_address": "10 Saligna Way\n\nDayton WA 6055\nAustralia",
        "partner_id_display_name": "Parvinder Singh",
        "partner_id_phone": "+61 401 196 596",
        "state": "sale",
        "x_studio_commission_paid": 0,
        "x_studio_invoice_payment_status": "0",
        "x_studio_payment_type": "Finance - Humm",
        "x_studio_referrer_processed": 0,
        "x_studio_sales_rep_1": "Terry Warby",
        "x_studio_sales_source": "Company Lead",
        "order_line": []
    }
]